//! This file is generated by `cargo codegen config`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]

mod utils;
#[test]
fn basic_entries() {
    let source = include_str!("../../../test-suite/basic-entries/input.mical");
    let expected_json = include_str!("../../../test-suite/basic-entries/output.json");
    let snapshot = utils::make_snapshot("basic-entries", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("basic-entries", source, expected_json);
}
#[test]
fn blank_lines_between_entries() {
    let source = include_str!("../../../test-suite/blank-lines-between-entries/input.mical");
    let expected_json = include_str!("../../../test-suite/blank-lines-between-entries/output.json");
    let snapshot = utils::make_snapshot("blank-lines-between-entries", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("blank-lines-between-entries", source, expected_json);
}
#[test]
fn block_string_blank_lines_within() {
    let source = include_str!("../../../test-suite/block-string-blank-lines-within/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-blank-lines-within/output.json");
    let snapshot = utils::make_snapshot("block-string-blank-lines-within", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-blank-lines-within", source, expected_json);
}
#[test]
fn block_string_chomp_keep_trailing() {
    let source = include_str!("../../../test-suite/block-string-chomp-keep-trailing/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-chomp-keep-trailing/output.json");
    let snapshot = utils::make_snapshot("block-string-chomp-keep-trailing", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-chomp-keep-trailing", source, expected_json);
}
#[test]
fn block_string_comment_literal_body() {
    let source = include_str!("../../../test-suite/block-string-comment-literal-body/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-comment-literal-body/output.json");
    let snapshot = utils::make_snapshot("block-string-comment-literal-body", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-comment-literal-body", source, expected_json);
}
#[test]
fn block_string_eof_end() {
    let source = include_str!("../../../test-suite/block-string-eof-end/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-eof-end/output.json");
    let snapshot = utils::make_snapshot("block-string-eof-end", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-eof-end", source, expected_json);
}
#[test]
fn block_string_explicit_indent() {
    let source = include_str!("../../../test-suite/block-string-explicit-indent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-explicit-indent/output.json");
    let snapshot = utils::make_snapshot("block-string-explicit-indent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-explicit-indent", source, expected_json);
}
#[test]
fn block_string_explicit_indent_empty_first() {
    let source = include_str!("../../../test-suite/block-string-explicit-indent-empty-first/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-explicit-indent-empty-first/output.json");
    let snapshot = utils::make_snapshot("block-string-explicit-indent-empty-first", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-explicit-indent-empty-first", source, expected_json);
}
#[test]
fn block_string_folded_basic() {
    let source = include_str!("../../../test-suite/block-string-folded-basic/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-folded-basic/output.json");
    let snapshot = utils::make_snapshot("block-string-folded-basic", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-folded-basic", source, expected_json);
}
#[test]
fn block_string_folded_indented_suppression() {
    let source = include_str!("../../../test-suite/block-string-folded-indented-suppression/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-folded-indented-suppression/output.json");
    let snapshot = utils::make_snapshot("block-string-folded-indented-suppression", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-folded-indented-suppression", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-clip-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-clip-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-clip-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_simple_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-simple-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-clip-simple-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-simple-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-simple-eof", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_simple_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-simple-eof-nonl/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-clip-simple-eof-nonl/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-simple-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-simple-eof-nonl", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_tab_content_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-tab-content-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-clip-tab-content-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-tab-content-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-tab-content-eof", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-clip-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-clip-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-clip-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-clip-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_i2_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-i2-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-i2-clip-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_i2_clip_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-i2-clip-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-i2-clip-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-i2-clip-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_i2_clip_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-i2-clip-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-i2-clip-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_i2_clip_tab_content_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-tab-content-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-i2-clip-tab-content-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-i2-clip-tab-content-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-i2-clip-tab-content-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_i2_clip_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-i2-clip-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-i2-clip-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-i2-clip-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_i2_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-i2-clip-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-i2-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-i2-clip-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_keep_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-keep-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-keep-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-keep-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-keep-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_keep_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-keep-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-keep-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-keep-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-keep-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_keep_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-keep-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-keep-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-keep-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-keep-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_keep_simple_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-keep-simple-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-keep-simple-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-keep-simple-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-keep-simple-eof", source, expected_json);
}
#[test]
fn block_string_gen_folded_keep_simple_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-keep-simple-eof-nonl/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-keep-simple-eof-nonl/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-keep-simple-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-keep-simple-eof-nonl", source, expected_json);
}
#[test]
fn block_string_gen_folded_keep_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-keep-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-keep-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-keep-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-keep-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_keep_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-keep-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-keep-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-keep-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-keep-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_strip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-strip-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-strip-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-strip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-strip-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_strip_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-strip-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-strip-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-strip-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-strip-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_strip_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-strip-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-strip-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-strip-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-strip-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_strip_simple_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-strip-simple-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-strip-simple-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-strip-simple-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-strip-simple-eof", source, expected_json);
}
#[test]
fn block_string_gen_folded_strip_simple_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-strip-simple-eof-nonl/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-strip-simple-eof-nonl/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-strip-simple-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-strip-simple-eof-nonl", source, expected_json);
}
#[test]
fn block_string_gen_folded_strip_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-strip-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-folded-strip-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-strip-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-strip-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_folded_strip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-folded-strip-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-folded-strip-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-folded-strip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-folded-strip-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-clip-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-clip-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-clip-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_simple_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-simple-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-clip-simple-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-simple-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-simple-eof", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_simple_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-simple-eof-nonl/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-clip-simple-eof-nonl/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-simple-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-simple-eof-nonl", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_tab_content_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-tab-content-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-clip-tab-content-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-tab-content-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-tab-content-eof", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-clip-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-clip-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-clip-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-clip-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_i2_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-i2-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-i2-clip-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_i2_clip_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-i2-clip-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-i2-clip-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-i2-clip-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_i2_clip_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-i2-clip-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-i2-clip-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_i2_clip_tab_content_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-tab-content-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-i2-clip-tab-content-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-i2-clip-tab-content-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-i2-clip-tab-content-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_i2_clip_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-i2-clip-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-i2-clip-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-i2-clip-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_i2_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-i2-clip-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-i2-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-i2-clip-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_keep_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-keep-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-keep-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-keep-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-keep-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_keep_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-keep-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-keep-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-keep-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-keep-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_keep_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-keep-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-keep-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-keep-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-keep-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_keep_simple_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-keep-simple-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-keep-simple-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-keep-simple-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-keep-simple-eof", source, expected_json);
}
#[test]
fn block_string_gen_literal_keep_simple_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-keep-simple-eof-nonl/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-keep-simple-eof-nonl/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-keep-simple-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-keep-simple-eof-nonl", source, expected_json);
}
#[test]
fn block_string_gen_literal_keep_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-keep-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-keep-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-keep-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-keep-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_keep_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-keep-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-keep-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-keep-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-keep-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_strip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-strip-emptyln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-strip-emptyln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-strip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-strip-emptyln-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_strip_extra_indent_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-strip-extra-indent-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-strip-extra-indent-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-strip-extra-indent-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-strip-extra-indent-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_strip_simple_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-strip-simple-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-strip-simple-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-strip-simple-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-strip-simple-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_strip_simple_eof() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-strip-simple-eof/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-strip-simple-eof/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-strip-simple-eof", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-strip-simple-eof", source, expected_json);
}
#[test]
fn block_string_gen_literal_strip_simple_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-strip-simple-eof-nonl/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-strip-simple-eof-nonl/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-strip-simple-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-strip-simple-eof-nonl", source, expected_json);
}
#[test]
fn block_string_gen_literal_strip_trailing_empty_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-strip-trailing-empty-dedent/input.mical");
    let expected_json =
        include_str!("../../../test-suite/block-string-gen-literal-strip-trailing-empty-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-strip-trailing-empty-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-strip-trailing-empty-dedent", source, expected_json);
}
#[test]
fn block_string_gen_literal_strip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-gen-literal-strip-wsln-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-gen-literal-strip-wsln-dedent/output.json");
    let snapshot = utils::make_snapshot("block-string-gen-literal-strip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-gen-literal-strip-wsln-dedent", source, expected_json);
}
#[test]
fn block_string_header_comment() {
    let source = include_str!("../../../test-suite/block-string-header-comment/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-header-comment/output.json");
    let snapshot = utils::make_snapshot("block-string-header-comment", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-header-comment", source, expected_json);
}
#[test]
fn block_string_header_fallbacks() {
    let source = include_str!("../../../test-suite/block-string-header-fallbacks/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-header-fallbacks/output.json");
    let snapshot = utils::make_snapshot("block-string-header-fallbacks", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-header-fallbacks", source, expected_json);
}
#[test]
fn block_string_literal_basic() {
    let source = include_str!("../../../test-suite/block-string-literal-basic/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-literal-basic/output.json");
    let snapshot = utils::make_snapshot("block-string-literal-basic", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-literal-basic", source, expected_json);
}
#[test]
fn block_string_tabs_literal() {
    let source = include_str!("../../../test-suite/block-string-tabs-literal/input.mical");
    let expected_json = include_str!("../../../test-suite/block-string-tabs-literal/output.json");
    let snapshot = utils::make_snapshot("block-string-tabs-literal", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("block-string-tabs-literal", source, expected_json);
}
#[test]
fn comment_full_line() {
    let source = include_str!("../../../test-suite/comment-full-line/input.mical");
    let expected_json = include_str!("../../../test-suite/comment-full-line/output.json");
    let snapshot = utils::make_snapshot("comment-full-line", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("comment-full-line", source, expected_json);
}
#[test]
fn comment_hash_literal() {
    let source = include_str!("../../../test-suite/comment-hash-literal/input.mical");
    let expected_json = include_str!("../../../test-suite/comment-hash-literal/output.json");
    let snapshot = utils::make_snapshot("comment-hash-literal", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("comment-hash-literal", source, expected_json);
}
#[test]
fn comment_indented_hash_word() {
    let source = include_str!("../../../test-suite/comment-indented-hash-word/input.mical");
    let expected_json = include_str!("../../../test-suite/comment-indented-hash-word/output.json");
    let snapshot = utils::make_snapshot("comment-indented-hash-word", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("comment-indented-hash-word", source, expected_json);
}
#[test]
fn comment_inline() {
    let source = include_str!("../../../test-suite/comment-inline/input.mical");
    let expected_json = include_str!("../../../test-suite/comment-inline/output.json");
    let snapshot = utils::make_snapshot("comment-inline", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("comment-inline", source, expected_json);
}
#[test]
fn crlf_line_endings() {
    let source = include_str!("../../../test-suite/crlf-line-endings/input.mical");
    let expected_json = include_str!("../../../test-suite/crlf-line-endings/output.json");
    let snapshot = utils::make_snapshot("crlf-line-endings", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("crlf-line-endings", source, expected_json);
}
#[test]
fn directive_basic() {
    let source = include_str!("../../../test-suite/directive-basic/input.mical");
    let expected_json = include_str!("../../../test-suite/directive-basic/output.json");
    let snapshot = utils::make_snapshot("directive-basic", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("directive-basic", source, expected_json);
}
#[test]
fn directive_no_args() {
    let source = include_str!("../../../test-suite/directive-no-args/input.mical");
    let expected_json = include_str!("../../../test-suite/directive-no-args/output.json");
    let snapshot = utils::make_snapshot("directive-no-args", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("directive-no-args", source, expected_json);
}
#[test]
fn directive_shebang_style() {
    let source = include_str!("../../../test-suite/directive-shebang-style/input.mical");
    let expected_json = include_str!("../../../test-suite/directive-shebang-style/output.json");
    let snapshot = utils::make_snapshot("directive-shebang-style", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("directive-shebang-style", source, expected_json);
}
#[test]
fn empty() {
    let source = include_str!("../../../test-suite/empty/input.mical");
    let expected_json = include_str!("../../../test-suite/empty/output.json");
    let snapshot = utils::make_snapshot("empty", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("empty", source, expected_json);
}
#[test]
fn error_block_string_empty_inference() {
    let source = include_str!("../../../test-suite/error-block-string-empty-inference/input.mical");
    let expected_json = include_str!("../../../test-suite/error-block-string-empty-inference/output.json");
    let snapshot = utils::make_snapshot("error-block-string-empty-inference", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-block-string-empty-inference", source, expected_json);
}
#[test]
fn error_block_string_insufficient_indent() {
    let source = include_str!("../../../test-suite/error-block-string-insufficient-indent/input.mical");
    let expected_json = include_str!("../../../test-suite/error-block-string-insufficient-indent/output.json");
    let snapshot = utils::make_snapshot("error-block-string-insufficient-indent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-block-string-insufficient-indent", source, expected_json);
}
#[test]
fn error_key_junk_after_quote() {
    let source = include_str!("../../../test-suite/error-key-junk-after-quote/input.mical");
    let expected_json = include_str!("../../../test-suite/error-key-junk-after-quote/output.json");
    let snapshot = utils::make_snapshot("error-key-junk-after-quote", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-key-junk-after-quote", source, expected_json);
}
#[test]
fn error_key_missing_value() {
    let source = include_str!("../../../test-suite/error-key-missing-value/input.mical");
    let expected_json = include_str!("../../../test-suite/error-key-missing-value/output.json");
    let snapshot = utils::make_snapshot("error-key-missing-value", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-key-missing-value", source, expected_json);
}
#[test]
fn error_key_missing_value_after_comment() {
    let source = include_str!("../../../test-suite/error-key-missing-value-after-comment/input.mical");
    let expected_json = include_str!("../../../test-suite/error-key-missing-value-after-comment/output.json");
    let snapshot = utils::make_snapshot("error-key-missing-value-after-comment", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-key-missing-value-after-comment", source, expected_json);
}
#[test]
fn error_key_tab_separator() {
    let source = include_str!("../../../test-suite/error-key-tab-separator/input.mical");
    let expected_json = include_str!("../../../test-suite/error-key-tab-separator/output.json");
    let snapshot = utils::make_snapshot("error-key-tab-separator", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-key-tab-separator", source, expected_json);
}
#[test]
fn error_key_unclosed_quote() {
    let source = include_str!("../../../test-suite/error-key-unclosed-quote/input.mical");
    let expected_json = include_str!("../../../test-suite/error-key-unclosed-quote/output.json");
    let snapshot = utils::make_snapshot("error-key-unclosed-quote", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-key-unclosed-quote", source, expected_json);
}
#[test]
fn error_prefix_block_indent_mismatch() {
    let source = include_str!("../../../test-suite/error-prefix-block-indent-mismatch/input.mical");
    let expected_json = include_str!("../../../test-suite/error-prefix-block-indent-mismatch/output.json");
    let snapshot = utils::make_snapshot("error-prefix-block-indent-mismatch", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-prefix-block-indent-mismatch", source, expected_json);
}
#[test]
fn error_tab_indent() {
    let source = include_str!("../../../test-suite/error-tab-indent/input.mical");
    let expected_json = include_str!("../../../test-suite/error-tab-indent/output.json");
    let snapshot = utils::make_snapshot("error-tab-indent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-tab-indent", source, expected_json);
}
#[test]
fn error_unexpected_indentation() {
    let source = include_str!("../../../test-suite/error-unexpected-indentation/input.mical");
    let expected_json = include_str!("../../../test-suite/error-unexpected-indentation/output.json");
    let snapshot = utils::make_snapshot("error-unexpected-indentation", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-unexpected-indentation", source, expected_json);
}
#[test]
fn error_value_junk_after_quoted() {
    let source = include_str!("../../../test-suite/error-value-junk-after-quoted/input.mical");
    let expected_json = include_str!("../../../test-suite/error-value-junk-after-quoted/output.json");
    let snapshot = utils::make_snapshot("error-value-junk-after-quoted", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-value-junk-after-quoted", source, expected_json);
}
#[test]
fn error_value_unclosed_quote() {
    let source = include_str!("../../../test-suite/error-value-unclosed-quote/input.mical");
    let expected_json = include_str!("../../../test-suite/error-value-unclosed-quote/output.json");
    let snapshot = utils::make_snapshot("error-value-unclosed-quote", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("error-value-unclosed-quote", source, expected_json);
}
#[test]
fn key_multi_space_separator() {
    let source = include_str!("../../../test-suite/key-multi-space-separator/input.mical");
    let expected_json = include_str!("../../../test-suite/key-multi-space-separator/output.json");
    let snapshot = utils::make_snapshot("key-multi-space-separator", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("key-multi-space-separator", source, expected_json);
}
#[test]
fn key_punctuation() {
    let source = include_str!("../../../test-suite/key-punctuation/input.mical");
    let expected_json = include_str!("../../../test-suite/key-punctuation/output.json");
    let snapshot = utils::make_snapshot("key-punctuation", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("key-punctuation", source, expected_json);
}
#[test]
fn key_quoted_basic() {
    let source = include_str!("../../../test-suite/key-quoted-basic/input.mical");
    let expected_json = include_str!("../../../test-suite/key-quoted-basic/output.json");
    let snapshot = utils::make_snapshot("key-quoted-basic", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("key-quoted-basic", source, expected_json);
}
#[test]
fn key_quoted_escapes() {
    let source = include_str!("../../../test-suite/key-quoted-escapes/input.mical");
    let expected_json = include_str!("../../../test-suite/key-quoted-escapes/output.json");
    let snapshot = utils::make_snapshot("key-quoted-escapes", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("key-quoted-escapes", source, expected_json);
}
#[test]
fn key_quoted_spaces_hash() {
    let source = include_str!("../../../test-suite/key-quoted-spaces-hash/input.mical");
    let expected_json = include_str!("../../../test-suite/key-quoted-spaces-hash/output.json");
    let snapshot = utils::make_snapshot("key-quoted-spaces-hash", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("key-quoted-spaces-hash", source, expected_json);
}
#[test]
fn key_typed_lookalikes() {
    let source = include_str!("../../../test-suite/key-typed-lookalikes/input.mical");
    let expected_json = include_str!("../../../test-suite/key-typed-lookalikes/output.json");
    let snapshot = utils::make_snapshot("key-typed-lookalikes", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("key-typed-lookalikes", source, expected_json);
}
#[test]
fn prefix_block_basic() {
    let source = include_str!("../../../test-suite/prefix-block-basic/input.mical");
    let expected_json = include_str!("../../../test-suite/prefix-block-basic/output.json");
    let snapshot = utils::make_snapshot("prefix-block-basic", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("prefix-block-basic", source, expected_json);
}
#[test]
fn prefix_block_col0_comment_inside() {
    let source = include_str!("../../../test-suite/prefix-block-col0-comment-inside/input.mical");
    let expected_json = include_str!("../../../test-suite/prefix-block-col0-comment-inside/output.json");
    let snapshot = utils::make_snapshot("prefix-block-col0-comment-inside", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("prefix-block-col0-comment-inside", source, expected_json);
}
#[test]
fn prefix_block_directive_closes_block() {
    let source = include_str!("../../../test-suite/prefix-block-directive-closes-block/input.mical");
    let expected_json = include_str!("../../../test-suite/prefix-block-directive-closes-block/output.json");
    let snapshot = utils::make_snapshot("prefix-block-directive-closes-block", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("prefix-block-directive-closes-block", source, expected_json);
}
#[test]
fn prefix_block_mixed_values() {
    let source = include_str!("../../../test-suite/prefix-block-mixed-values/input.mical");
    let expected_json = include_str!("../../../test-suite/prefix-block-mixed-values/output.json");
    let snapshot = utils::make_snapshot("prefix-block-mixed-values", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("prefix-block-mixed-values", source, expected_json);
}
#[test]
fn prefix_block_nested_multi_dedent() {
    let source = include_str!("../../../test-suite/prefix-block-nested-multi-dedent/input.mical");
    let expected_json = include_str!("../../../test-suite/prefix-block-nested-multi-dedent/output.json");
    let snapshot = utils::make_snapshot("prefix-block-nested-multi-dedent", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("prefix-block-nested-multi-dedent", source, expected_json);
}
#[test]
fn prefix_block_opener_inline_comment() {
    let source = include_str!("../../../test-suite/prefix-block-opener-inline-comment/input.mical");
    let expected_json = include_str!("../../../test-suite/prefix-block-opener-inline-comment/output.json");
    let snapshot = utils::make_snapshot("prefix-block-opener-inline-comment", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("prefix-block-opener-inline-comment", source, expected_json);
}
#[test]
fn prefix_block_opener_quoted_key() {
    let source = include_str!("../../../test-suite/prefix-block-opener-quoted-key/input.mical");
    let expected_json = include_str!("../../../test-suite/prefix-block-opener-quoted-key/output.json");
    let snapshot = utils::make_snapshot("prefix-block-opener-quoted-key", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("prefix-block-opener-quoted-key", source, expected_json);
}
#[test]
fn trailing_spaces_stripped() {
    let source = include_str!("../../../test-suite/trailing-spaces-stripped/input.mical");
    let expected_json = include_str!("../../../test-suite/trailing-spaces-stripped/output.json");
    let snapshot = utils::make_snapshot("trailing-spaces-stripped", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("trailing-spaces-stripped", source, expected_json);
}
#[test]
fn value_boolean() {
    let source = include_str!("../../../test-suite/value-boolean/input.mical");
    let expected_json = include_str!("../../../test-suite/value-boolean/output.json");
    let snapshot = utils::make_snapshot("value-boolean", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-boolean", source, expected_json);
}
#[test]
fn value_boolean_fallback() {
    let source = include_str!("../../../test-suite/value-boolean-fallback/input.mical");
    let expected_json = include_str!("../../../test-suite/value-boolean-fallback/output.json");
    let snapshot = utils::make_snapshot("value-boolean-fallback", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-boolean-fallback", source, expected_json);
}
#[test]
fn value_integer_fallback() {
    let source = include_str!("../../../test-suite/value-integer-fallback/input.mical");
    let expected_json = include_str!("../../../test-suite/value-integer-fallback/output.json");
    let snapshot = utils::make_snapshot("value-integer-fallback", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-integer-fallback", source, expected_json);
}
#[test]
fn value_integer_radixes() {
    let source = include_str!("../../../test-suite/value-integer-radixes/input.mical");
    let expected_json = include_str!("../../../test-suite/value-integer-radixes/output.json");
    let snapshot = utils::make_snapshot("value-integer-radixes", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-integer-radixes", source, expected_json);
}
#[test]
fn value_line_string_literal_punctuation() {
    let source = include_str!("../../../test-suite/value-line-string-literal-punctuation/input.mical");
    let expected_json = include_str!("../../../test-suite/value-line-string-literal-punctuation/output.json");
    let snapshot = utils::make_snapshot("value-line-string-literal-punctuation", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-line-string-literal-punctuation", source, expected_json);
}
#[test]
fn value_line_string_midquote_comment() {
    let source = include_str!("../../../test-suite/value-line-string-midquote-comment/input.mical");
    let expected_json = include_str!("../../../test-suite/value-line-string-midquote-comment/output.json");
    let snapshot = utils::make_snapshot("value-line-string-midquote-comment", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-line-string-midquote-comment", source, expected_json);
}
#[test]
fn value_quoted_escapes() {
    let source = include_str!("../../../test-suite/value-quoted-escapes/input.mical");
    let expected_json = include_str!("../../../test-suite/value-quoted-escapes/output.json");
    let snapshot = utils::make_snapshot("value-quoted-escapes", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-quoted-escapes", source, expected_json);
}
#[test]
fn value_quoted_hash_inside() {
    let source = include_str!("../../../test-suite/value-quoted-hash-inside/input.mical");
    let expected_json = include_str!("../../../test-suite/value-quoted-hash-inside/output.json");
    let snapshot = utils::make_snapshot("value-quoted-hash-inside", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-quoted-hash-inside", source, expected_json);
}
#[test]
fn value_typed_with_inline_comment() {
    let source = include_str!("../../../test-suite/value-typed-with-inline-comment/input.mical");
    let expected_json = include_str!("../../../test-suite/value-typed-with-inline-comment/output.json");
    let snapshot = utils::make_snapshot("value-typed-with-inline-comment", source);
    utils::assert_snapshot!(snapshot);
    utils::assert_json_output("value-typed-with-inline-comment", source, expected_json);
}
