//! This file is generated by `cargo codegen parser`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]

mod utils;
#[test]
fn blank_line_in_prefix_block() {
    let source = include_str!("../../../test-suite/blank-line-in-prefix-block/input.mical");
    let snapshot = utils::make_snapshot("blank-line-in-prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn blank_lines_between_entries() {
    let source = include_str!("../../../test-suite/blank-lines-between-entries/input.mical");
    let snapshot = utils::make_snapshot("blank-lines-between-entries", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_clip_emptyln_none_eof() {
    let source = include_str!("../../../test-suite/block-string-1-folded-clip-emptyln-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-clip-emptyln-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_clip_none_emptyln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-folded-clip-none-emptyln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-clip-none-emptyln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_keep_emptyln_wsln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-folded-keep-emptyln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-keep-emptyln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_keep_none_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-folded-keep-none-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-keep-none-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_strip_emptyln_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-folded-strip-emptyln-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-strip-emptyln-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_strip_wsln_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-folded-strip-wsln-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-strip-wsln-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_emptyln_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-emptyln-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-emptyln-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_emptyln_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-emptyln-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-emptyln-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_none_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-none-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-none-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_wsln_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-wsln-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-wsln-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_keep_emptyln_wsln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-keep-emptyln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-keep-emptyln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_keep_wsln_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-literal-keep-wsln-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-keep-wsln-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_keep_wsln_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-keep-wsln-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-keep-wsln-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_strip_emptyln_emptyln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-strip-emptyln-emptyln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-strip-emptyln-emptyln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_strip_none_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-literal-strip-none-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-strip-none-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_strip_none_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-literal-strip-none-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-strip-none-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_body_trailing_whitespace() {
    let source = include_str!("../../../test-suite/block-string-body-trailing-whitespace/input.mical");
    let snapshot = utils::make_snapshot("block-string-body-trailing-whitespace", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_clip_multi_trailing() {
    let source = include_str!("../../../test-suite/block-string-clip-multi-trailing/input.mical");
    let snapshot = utils::make_snapshot("block-string-clip-multi-trailing", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_extra_indent() {
    let source = include_str!("../../../test-suite/block-string-extra-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-extra-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_fallback() {
    let source = include_str!("../../../test-suite/block-string-fallback/input.mical");
    let snapshot = utils::make_snapshot("block-string-fallback", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded() {
    let source = include_str!("../../../test-suite/block-string-folded/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded_extra_indent_clip() {
    let source = include_str!("../../../test-suite/block-string-folded-extra-indent-clip/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded-extra-indent-clip", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded_extra_indent_consecutive() {
    let source = include_str!("../../../test-suite/block-string-folded-extra-indent-consecutive/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded-extra-indent-consecutive", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded_extra_indent_empty_line() {
    let source = include_str!("../../../test-suite/block-string-folded-extra-indent-empty-line/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded-extra-indent-empty-line", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded_extra_indent_keep() {
    let source = include_str!("../../../test-suite/block-string-folded-extra-indent-keep/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded-extra-indent-keep", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded_extra_indent_strip() {
    let source = include_str!("../../../test-suite/block-string-folded-extra-indent-strip/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded-extra-indent-strip", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_header_trailing_space() {
    let source = include_str!("../../../test-suite/block-string-header-trailing-space/input.mical");
    let snapshot = utils::make_snapshot("block-string-header-trailing-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_in_prefix() {
    let source = include_str!("../../../test-suite/block-string-in-prefix/input.mical");
    let snapshot = utils::make_snapshot("block-string-in-prefix", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_indent() {
    let source = include_str!("../../../test-suite/block-string-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_indicator_fallback() {
    let source = include_str!("../../../test-suite/block-string-indicator-fallback/input.mical");
    let snapshot = utils::make_snapshot("block-string-indicator-fallback", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_insufficient_indent() {
    let source = include_str!("../../../test-suite/block-string-insufficient-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-insufficient-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_keep_multi_trailing() {
    let source = include_str!("../../../test-suite/block-string-keep-multi-trailing/input.mical");
    let snapshot = utils::make_snapshot("block-string-keep-multi-trailing", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_clip_emptyln_none_wsln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-clip-emptyln-none-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-clip-emptyln-none-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_clip_wsln_emptyln_emptyln_eof() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-clip-wsln-emptyln-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-clip-wsln-emptyln-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_keep_emptyln_emptyln_none_dedent() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-keep-emptyln-emptyln-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-keep-emptyln-emptyln-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_keep_emptyln_wsln_none_eof() {
    let source = include_str!("../../../test-suite/block-string-multi-folded-keep-emptyln-wsln-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-keep-emptyln-wsln-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_keep_wsln_wsln_emptyln_dedent() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-keep-wsln-wsln-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-keep-wsln-wsln-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_strip_emptyln_emptyln_wsln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-strip-emptyln-emptyln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-strip-emptyln-emptyln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_strip_none_wsln_emptyln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-strip-none-wsln-emptyln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-strip-none-wsln-emptyln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_strip_wsln_none_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-multi-folded-strip-wsln-none-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-strip-wsln-none-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_clip_none_wsln_wsln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-literal-clip-none-wsln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-clip-none-wsln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_clip_wsln_wsln_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-multi-literal-clip-wsln-wsln-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-clip-wsln-wsln-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_keep_none_emptyln_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-multi-literal-keep-none-emptyln-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-keep-none-emptyln-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_keep_wsln_none_none_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-literal-keep-wsln-none-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-keep-wsln-none-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_strip_emptyln_none_emptyln_eof() {
    let source =
        include_str!("../../../test-suite/block-string-multi-literal-strip-emptyln-none-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-strip-emptyln-none-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_strip_none_none_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-multi-literal-strip-none-none-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-strip-none-none-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_nested_edge_cases() {
    let source = include_str!("../../../test-suite/block-string-nested-edge-cases/input.mical");
    let snapshot = utils::make_snapshot("block-string-nested-edge-cases", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_nested_indent() {
    let source = include_str!("../../../test-suite/block-string-nested-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-nested-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_tab_after_content() {
    let source = include_str!("../../../test-suite/block-string-tab-after-content/input.mical");
    let snapshot = utils::make_snapshot("block-string-tab-after-content", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_wsln_above_base() {
    let source = include_str!("../../../test-suite/block-string-wsln-above-base/input.mical");
    let snapshot = utils::make_snapshot("block-string-wsln-above-base", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn boolean_multiple_trailing_spaces() {
    let source = include_str!("../../../test-suite/boolean-multiple-trailing-spaces/input.mical");
    let snapshot = utils::make_snapshot("boolean-multiple-trailing-spaces", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn brace_after_key() {
    let source = include_str!("../../../test-suite/brace-after-key/input.mical");
    let snapshot = utils::make_snapshot("brace-after-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn brace_alone_as_key() {
    let source = include_str!("../../../test-suite/brace-alone-as-key/input.mical");
    let snapshot = utils::make_snapshot("brace-alone-as-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn brace_not_block() {
    let source = include_str!("../../../test-suite/brace-not-block/input.mical");
    let snapshot = utils::make_snapshot("brace-not-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn close_brace_deeply_indented() {
    let source = include_str!("../../../test-suite/close-brace-deeply-indented/input.mical");
    let snapshot = utils::make_snapshot("close-brace-deeply-indented", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn close_brace_with_content() {
    let source = include_str!("../../../test-suite/close-brace-with-content/input.mical");
    let snapshot = utils::make_snapshot("close-brace-with-content", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn close_brace_word_after() {
    let source = include_str!("../../../test-suite/close-brace-word-after/input.mical");
    let snapshot = utils::make_snapshot("close-brace-word-after", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_after_close_brace() {
    let source = include_str!("../../../test-suite/comment-after-close-brace/input.mical");
    let snapshot = utils::make_snapshot("comment-after-close-brace", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_at_eof() {
    let source = include_str!("../../../test-suite/comment-at-eof/input.mical");
    let snapshot = utils::make_snapshot("comment-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_between_blocks() {
    let source = include_str!("../../../test-suite/comment-between-blocks/input.mical");
    let snapshot = utils::make_snapshot("comment-between-blocks", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_consecutive() {
    let source = include_str!("../../../test-suite/comment-consecutive/input.mical");
    let snapshot = utils::make_snapshot("comment-consecutive", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_deeply_indented() {
    let source = include_str!("../../../test-suite/comment-deeply-indented/input.mical");
    let snapshot = utils::make_snapshot("comment-deeply-indented", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_hash_at_eof() {
    let source = include_str!("../../../test-suite/comment-hash-at-eof/input.mical");
    let snapshot = utils::make_snapshot("comment-hash-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_hash_non_word() {
    let source = include_str!("../../../test-suite/comment-hash-non-word/input.mical");
    let snapshot = utils::make_snapshot("comment-hash-non-word", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_indented() {
    let source = include_str!("../../../test-suite/comment-indented/input.mical");
    let snapshot = utils::make_snapshot("comment-indented", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_only_in_prefix_block() {
    let source = include_str!("../../../test-suite/comment-only-in-prefix-block/input.mical");
    let snapshot = utils::make_snapshot("comment-only-in-prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comment_special_chars() {
    let source = include_str!("../../../test-suite/comment-special-chars/input.mical");
    let snapshot = utils::make_snapshot("comment-special-chars", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comments_directives() {
    let source = include_str!("../../../test-suite/comments-directives/input.mical");
    let snapshot = utils::make_snapshot("comments-directives", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn crlf_basic() {
    let source = include_str!("../../../test-suite/crlf-basic/input.mical");
    let snapshot = utils::make_snapshot("crlf-basic", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn crlf_mixed() {
    let source = include_str!("../../../test-suite/crlf-mixed/input.mical");
    let snapshot = utils::make_snapshot("crlf-mixed", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn directive() {
    let source = include_str!("../../../test-suite/directive/input.mical");
    let snapshot = utils::make_snapshot("directive", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn directive_at_eof() {
    let source = include_str!("../../../test-suite/directive-at-eof/input.mical");
    let snapshot = utils::make_snapshot("directive-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn directive_in_prefix_block() {
    let source = include_str!("../../../test-suite/directive-in-prefix-block/input.mical");
    let snapshot = utils::make_snapshot("directive-in-prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn directive_no_args() {
    let source = include_str!("../../../test-suite/directive-no-args/input.mical");
    let snapshot = utils::make_snapshot("directive-no-args", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn duplicate_keys() {
    let source = include_str!("../../../test-suite/duplicate-keys/input.mical");
    let snapshot = utils::make_snapshot("duplicate-keys", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn duplicate_keys_mixed_types() {
    let source = include_str!("../../../test-suite/duplicate-keys-mixed-types/input.mical");
    let snapshot = utils::make_snapshot("duplicate-keys-mixed-types", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn duplicate_keys_nested_collision() {
    let source = include_str!("../../../test-suite/duplicate-keys-nested-collision/input.mical");
    let snapshot = utils::make_snapshot("duplicate-keys-nested-collision", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn duplicate_keys_three_sources() {
    let source = include_str!("../../../test-suite/duplicate-keys-three-sources/input.mical");
    let snapshot = utils::make_snapshot("duplicate-keys-three-sources", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn duplicate_keys_with_prefix() {
    let source = include_str!("../../../test-suite/duplicate-keys-with-prefix/input.mical");
    let snapshot = utils::make_snapshot("duplicate-keys-with-prefix", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn eof_line_string() {
    let source = include_str!("../../../test-suite/eof-line-string/input.mical");
    let snapshot = utils::make_snapshot("eof-line-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn eof_missing_value() {
    let source = include_str!("../../../test-suite/eof-missing-value/input.mical");
    let snapshot = utils::make_snapshot("eof-missing-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn eof_multiple_entries() {
    let source = include_str!("../../../test-suite/eof-multiple-entries/input.mical");
    let snapshot = utils::make_snapshot("eof-multiple-entries", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn eof_quoted_key_no_value() {
    let source = include_str!("../../../test-suite/eof-quoted-key-no-value/input.mical");
    let snapshot = utils::make_snapshot("eof-quoted-key-no-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn error_multiple() {
    let source = include_str!("../../../test-suite/error-multiple/input.mical");
    let snapshot = utils::make_snapshot("error-multiple", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_blank_lines_only() {
    let source = include_str!("../../../test-suite/file-blank-lines-only/input.mical");
    let snapshot = utils::make_snapshot("file-blank-lines-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_comment_only() {
    let source = include_str!("../../../test-suite/file-comment-only/input.mical");
    let snapshot = utils::make_snapshot("file-comment-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_directive_only() {
    let source = include_str!("../../../test-suite/file-directive-only/input.mical");
    let snapshot = utils::make_snapshot("file-directive-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_empty() {
    let source = include_str!("../../../test-suite/file-empty/input.mical");
    let snapshot = utils::make_snapshot("file-empty", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_newline() {
    let source = include_str!("../../../test-suite/file-newline/input.mical");
    let snapshot = utils::make_snapshot("file-newline", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_space_only() {
    let source = include_str!("../../../test-suite/file-space-only/input.mical");
    let snapshot = utils::make_snapshot("file-space-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_spaces_only() {
    let source = include_str!("../../../test-suite/file-spaces-only/input.mical");
    let snapshot = utils::make_snapshot("file-spaces-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn file_tab_only() {
    let source = include_str!("../../../test-suite/file-tab-only/input.mical");
    let snapshot = utils::make_snapshot("file-tab-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn hash_edge() {
    let source = include_str!("../../../test-suite/hash-edge/input.mical");
    let snapshot = utils::make_snapshot("hash-edge", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn hash_newline_mid_file() {
    let source = include_str!("../../../test-suite/hash-newline-mid-file/input.mical");
    let snapshot = utils::make_snapshot("hash-newline-mid-file", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_binary() {
    let source = include_str!("../../../test-suite/integer-binary/input.mical");
    let snapshot = utils::make_snapshot("integer-binary", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_empty_radix() {
    let source = include_str!("../../../test-suite/integer-empty-radix/input.mical");
    let snapshot = utils::make_snapshot("integer-empty-radix", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_hex_extended() {
    let source = include_str!("../../../test-suite/integer-hex-extended/input.mical");
    let snapshot = utils::make_snapshot("integer-hex-extended", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_invalid_radix_digits() {
    let source = include_str!("../../../test-suite/integer-invalid-radix-digits/input.mical");
    let snapshot = utils::make_snapshot("integer-invalid-radix-digits", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_large() {
    let source = include_str!("../../../test-suite/integer-large/input.mical");
    let snapshot = utils::make_snapshot("integer-large", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_leading_zeros() {
    let source = include_str!("../../../test-suite/integer-leading-zeros/input.mical");
    let snapshot = utils::make_snapshot("integer-leading-zeros", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_multiple_trailing_spaces() {
    let source = include_str!("../../../test-suite/integer-multiple-trailing-spaces/input.mical");
    let snapshot = utils::make_snapshot("integer-multiple-trailing-spaces", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_octal() {
    let source = include_str!("../../../test-suite/integer-octal/input.mical");
    let snapshot = utils::make_snapshot("integer-octal", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_signed_radix() {
    let source = include_str!("../../../test-suite/integer-signed-radix/input.mical");
    let snapshot = utils::make_snapshot("integer-signed-radix", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn integer_underscore() {
    let source = include_str!("../../../test-suite/integer-underscore/input.mical");
    let snapshot = utils::make_snapshot("integer-underscore", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn invalid_escape() {
    let source = include_str!("../../../test-suite/invalid-escape/input.mical");
    let snapshot = utils::make_snapshot("invalid-escape", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn invalid_escape_multiple() {
    let source = include_str!("../../../test-suite/invalid-escape-multiple/input.mical");
    let snapshot = utils::make_snapshot("invalid-escape-multiple", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn invalid_escape_single_quote() {
    let source = include_str!("../../../test-suite/invalid-escape-single-quote/input.mical");
    let snapshot = utils::make_snapshot("invalid-escape-single-quote", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_boolean() {
    let source = include_str!("../../../test-suite/key-value-boolean/input.mical");
    let snapshot = utils::make_snapshot("key-value-boolean", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_boolean_at_eof() {
    let source = include_str!("../../../test-suite/key-value-boolean-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-boolean-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_boolean_like() {
    let source = include_str!("../../../test-suite/key-value-boolean-like/input.mical");
    let snapshot = utils::make_snapshot("key-value-boolean-like", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_brace_in_key() {
    let source = include_str!("../../../test-suite/key-value-brace-in-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-brace-in-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_hash_value() {
    let source = include_str!("../../../test-suite/key-value-hash-value/input.mical");
    let snapshot = utils::make_snapshot("key-value-hash-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_indented_quoted_key() {
    let source = include_str!("../../../test-suite/key-value-indented-quoted-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-indented-quoted-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_indented_word_key() {
    let source = include_str!("../../../test-suite/key-value-indented-word-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-indented-word-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_integer() {
    let source = include_str!("../../../test-suite/key-value-integer/input.mical");
    let snapshot = utils::make_snapshot("key-value-integer", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_integer_at_eof() {
    let source = include_str!("../../../test-suite/key-value-integer-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-integer-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_integer_like() {
    let source = include_str!("../../../test-suite/key-value-integer-like/input.mical");
    let snapshot = utils::make_snapshot("key-value-integer-like", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_line_string() {
    let source = include_str!("../../../test-suite/key-value-line-string/input.mical");
    let snapshot = utils::make_snapshot("key-value-line-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_missing_value() {
    let source = include_str!("../../../test-suite/key-value-missing-value/input.mical");
    let snapshot = utils::make_snapshot("key-value-missing-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_punct_key() {
    let source = include_str!("../../../test-suite/key-value-punct-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-punct-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_in_line_string() {
    let source = include_str!("../../../test-suite/key-value-quoted-in-line-string/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-in-line-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key() {
    let source = include_str!("../../../test-suite/key-value-quoted-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_empty() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-empty/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-empty", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_unclosed() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-unclosed/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-unclosed", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_unexpected() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-unexpected/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-unexpected", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_with_space() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-with-space/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-with-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_string() {
    let source = include_str!("../../../test-suite/key-value-quoted-string/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_value_at_eof() {
    let source = include_str!("../../../test-suite/key-value-quoted-value-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-value-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_value_trailing() {
    let source = include_str!("../../../test-suite/key-value-quoted-value-trailing/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-value-trailing", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_sign_integer_at_eof() {
    let source = include_str!("../../../test-suite/key-value-sign-integer-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-sign-integer-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_space_no_value() {
    let source = include_str!("../../../test-suite/key-value-space-no-value/input.mical");
    let snapshot = utils::make_snapshot("key-value-space-no-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_trailing_space() {
    let source = include_str!("../../../test-suite/key-value-trailing-space/input.mical");
    let snapshot = utils::make_snapshot("key-value-trailing-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_wide_separator() {
    let source = include_str!("../../../test-suite/key-value-wide-separator/input.mical");
    let snapshot = utils::make_snapshot("key-value-wide-separator", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_word_key() {
    let source = include_str!("../../../test-suite/key-value-word-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-word-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_word_dot_prefix() {
    let source = include_str!("../../../test-suite/key-word-dot-prefix/input.mical");
    let snapshot = utils::make_snapshot("key-word-dot-prefix", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_word_unicode() {
    let source = include_str!("../../../test-suite/key-word-unicode/input.mical");
    let snapshot = utils::make_snapshot("key-word-unicode", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn line_string_backslash_literal() {
    let source = include_str!("../../../test-suite/line-string-backslash-literal/input.mical");
    let snapshot = utils::make_snapshot("line-string-backslash-literal", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn line_string_close_brace() {
    let source = include_str!("../../../test-suite/line-string-close-brace/input.mical");
    let snapshot = utils::make_snapshot("line-string-close-brace", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn line_string_special_chars() {
    let source = include_str!("../../../test-suite/line-string-special-chars/input.mical");
    let snapshot = utils::make_snapshot("line-string-special-chars", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn line_string_unicode() {
    let source = include_str!("../../../test-suite/line-string-unicode/input.mical");
    let snapshot = utils::make_snapshot("line-string-unicode", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn mixed() {
    let source = include_str!("../../../test-suite/mixed/input.mical");
    let snapshot = utils::make_snapshot("mixed", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_block() {
    let source = include_str!("../../../test-suite/nested-prefix-block/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_empty_inner() {
    let source = include_str!("../../../test-suite/nested-prefix-empty-inner/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-empty-inner", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_entries_each_level() {
    let source = include_str!("../../../test-suite/nested-prefix-entries-each-level/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-entries-each-level", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_entry_after_inner() {
    let source = include_str!("../../../test-suite/nested-prefix-entry-after-inner/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-entry-after-inner", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_entry_before_inner() {
    let source = include_str!("../../../test-suite/nested-prefix-entry-before-inner/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-entry-before-inner", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_missing_inner_close() {
    let source = include_str!("../../../test-suite/nested-prefix-missing-inner-close/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-missing-inner-close", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_missing_outer_close() {
    let source = include_str!("../../../test-suite/nested-prefix-missing-outer-close/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-missing-outer-close", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_quoted_inner_key() {
    let source = include_str!("../../../test-suite/nested-prefix-quoted-inner-key/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-quoted-inner-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_sibling_blocks() {
    let source = include_str!("../../../test-suite/nested-prefix-sibling-blocks/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-sibling-blocks", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block() {
    let source = include_str!("../../../test-suite/prefix-block/input.mical");
    let snapshot = utils::make_snapshot("prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_after_entry() {
    let source = include_str!("../../../test-suite/prefix-block-after-entry/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-after-entry", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_block_string_nested() {
    let source = include_str!("../../../test-suite/prefix-block-block-string-nested/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-block-string-nested", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_close_brace_as_key() {
    let source = include_str!("../../../test-suite/prefix-block-close-brace-as-key/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-close-brace-as-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_comment() {
    let source = include_str!("../../../test-suite/prefix-block-comment/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-comment", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_deeply_nested() {
    let source = include_str!("../../../test-suite/prefix-block-deeply-nested/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-deeply-nested", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_duplicate_across() {
    let source = include_str!("../../../test-suite/prefix-block-duplicate-across/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-duplicate-across", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_duplicate_keys() {
    let source = include_str!("../../../test-suite/prefix-block-duplicate-keys/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-duplicate-keys", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_empty() {
    let source = include_str!("../../../test-suite/prefix-block-empty/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-empty", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_empty_key() {
    let source = include_str!("../../../test-suite/prefix-block-empty-key/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-empty-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_empty_with_eof() {
    let source = include_str!("../../../test-suite/prefix-block-empty-with-eof/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-empty-with-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_eof_no_newline() {
    let source = include_str!("../../../test-suite/prefix-block-eof-no-newline/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-eof-no-newline", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_hash_word() {
    let source = include_str!("../../../test-suite/prefix-block-hash-word/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-hash-word", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_indented_opening() {
    let source = include_str!("../../../test-suite/prefix-block-indented-opening/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-indented-opening", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_missing_close() {
    let source = include_str!("../../../test-suite/prefix-block-missing-close/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-missing-close", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_missing_close_with_eof() {
    let source = include_str!("../../../test-suite/prefix-block-missing-close-with-eof/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-missing-close-with-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_missing_value_inner() {
    let source = include_str!("../../../test-suite/prefix-block-missing-value-inner/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-missing-value-inner", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_multiple() {
    let source = include_str!("../../../test-suite/prefix-block-multiple/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-multiple", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_nested() {
    let source = include_str!("../../../test-suite/prefix-block-nested/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-nested", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_no_indent_body() {
    let source = include_str!("../../../test-suite/prefix-block-no-indent-body/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-no-indent-body", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_open_at_eof() {
    let source = include_str!("../../../test-suite/prefix-block-open-at-eof/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-open-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_quoted_key() {
    let source = include_str!("../../../test-suite/prefix-block-quoted-key/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-quoted-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_quoted_key_block_string() {
    let source = include_str!("../../../test-suite/prefix-block-quoted-key-block-string/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-quoted-key-block-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_tab_indent_inner() {
    let source = include_str!("../../../test-suite/prefix-block-tab-indent-inner/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-tab-indent-inner", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_tab_separator_inner() {
    let source = include_str!("../../../test-suite/prefix-block-tab-separator-inner/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-tab-separator-inner", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_trailing_space() {
    let source = include_str!("../../../test-suite/prefix-block-trailing-space/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-trailing-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_typed_keys() {
    let source = include_str!("../../../test-suite/prefix-block-typed-keys/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-typed-keys", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_unclosed_quote_inner() {
    let source = include_str!("../../../test-suite/prefix-block-unclosed-quote-inner/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-unclosed-quote-inner", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_values() {
    let source = include_str!("../../../test-suite/prefix-block-values/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-values", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_key_double_all_escapes() {
    let source = include_str!("../../../test-suite/quoted-key-double-all-escapes/input.mical");
    let snapshot = utils::make_snapshot("quoted-key-double-all-escapes", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_key_invalid_escape() {
    let source = include_str!("../../../test-suite/quoted-key-invalid-escape/input.mical");
    let snapshot = utils::make_snapshot("quoted-key-invalid-escape", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_key_single_all_escapes() {
    let source = include_str!("../../../test-suite/quoted-key-single-all-escapes/input.mical");
    let snapshot = utils::make_snapshot("quoted-key-single-all-escapes", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_keys() {
    let source = include_str!("../../../test-suite/quoted-keys/input.mical");
    let snapshot = utils::make_snapshot("quoted-keys", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_string_adjacent_escapes() {
    let source = include_str!("../../../test-suite/quoted-string-adjacent-escapes/input.mical");
    let snapshot = utils::make_snapshot("quoted-string-adjacent-escapes", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_string_double_all_escapes() {
    let source = include_str!("../../../test-suite/quoted-string-double-all-escapes/input.mical");
    let snapshot = utils::make_snapshot("quoted-string-double-all-escapes", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_string_escape_only() {
    let source = include_str!("../../../test-suite/quoted-string-escape-only/input.mical");
    let snapshot = utils::make_snapshot("quoted-string-escape-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_string_single_all_escapes() {
    let source = include_str!("../../../test-suite/quoted-string-single-all-escapes/input.mical");
    let snapshot = utils::make_snapshot("quoted-string-single-all-escapes", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_string_space_content() {
    let source = include_str!("../../../test-suite/quoted-string-space-content/input.mical");
    let snapshot = utils::make_snapshot("quoted-string-space-content", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_string_unclosed_at_eof() {
    let source = include_str!("../../../test-suite/quoted-string-unclosed-at-eof/input.mical");
    let snapshot = utils::make_snapshot("quoted-string-unclosed-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_string_unclosed_value() {
    let source = include_str!("../../../test-suite/quoted-string-unclosed-value/input.mical");
    let snapshot = utils::make_snapshot("quoted-string-unclosed-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_strings() {
    let source = include_str!("../../../test-suite/quoted-strings/input.mical");
    let snapshot = utils::make_snapshot("quoted-strings", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn shebang() {
    let source = include_str!("../../../test-suite/shebang/input.mical");
    let snapshot = utils::make_snapshot("shebang", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn shebang_no_trailing_newline() {
    let source = include_str!("../../../test-suite/shebang-no-trailing-newline/input.mical");
    let snapshot = utils::make_snapshot("shebang-no-trailing-newline", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn shebang_only() {
    let source = include_str!("../../../test-suite/shebang-only/input.mical");
    let snapshot = utils::make_snapshot("shebang-only", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn shebang_with_comment() {
    let source = include_str!("../../../test-suite/shebang-with-comment/input.mical");
    let snapshot = utils::make_snapshot("shebang-with-comment", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn tab_indent() {
    let source = include_str!("../../../test-suite/tab-indent/input.mical");
    let snapshot = utils::make_snapshot("tab-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn tab_only_line() {
    let source = include_str!("../../../test-suite/tab-only-line/input.mical");
    let snapshot = utils::make_snapshot("tab-only-line", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn tab_separator() {
    let source = include_str!("../../../test-suite/tab-separator/input.mical");
    let snapshot = utils::make_snapshot("tab-separator", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn typed_values() {
    let source = include_str!("../../../test-suite/typed-values/input.mical");
    let snapshot = utils::make_snapshot("typed-values", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn whitespace_only_line() {
    let source = include_str!("../../../test-suite/whitespace-only-line/input.mical");
    let snapshot = utils::make_snapshot("whitespace-only-line", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn whitespace_only_line_at_eof() {
    let source = include_str!("../../../test-suite/whitespace-only-line-at-eof/input.mical");
    let snapshot = utils::make_snapshot("whitespace-only-line-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn whitespace_only_line_at_start() {
    let source = include_str!("../../../test-suite/whitespace-only-line-at-start/input.mical");
    let snapshot = utils::make_snapshot("whitespace-only-line-at-start", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn whitespace_only_line_in_prefix_block() {
    let source = include_str!("../../../test-suite/whitespace-only-line-in-prefix-block/input.mical");
    let snapshot = utils::make_snapshot("whitespace-only-line-in-prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn whitespace_only_lines_consecutive() {
    let source = include_str!("../../../test-suite/whitespace-only-lines-consecutive/input.mical");
    let snapshot = utils::make_snapshot("whitespace-only-lines-consecutive", source);
    utils::assert_snapshot!(snapshot);
}
