//! This file is generated by `cargo codegen parser`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]

mod utils;
const GROUP: &str = "block_string";
#[test]
fn basic() {
    let source = include_str!("./cases/block_string/basic.mical");
    let snapshot = utils::make_snapshot("block_string/basic", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn chomp_keep() {
    let source = include_str!("./cases/block_string/chomp_keep.mical");
    let snapshot = utils::make_snapshot("block_string/chomp_keep", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn chomp_keep_trailing() {
    let source = include_str!("./cases/block_string/chomp_keep_trailing.mical");
    let snapshot = utils::make_snapshot("block_string/chomp_keep_trailing", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn chomp_strip() {
    let source = include_str!("./cases/block_string/chomp_strip.mical");
    let snapshot = utils::make_snapshot("block_string/chomp_strip", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn empty() {
    let source = include_str!("./cases/block_string/empty.mical");
    let snapshot = utils::make_snapshot("block_string/empty", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn empty_line() {
    let source = include_str!("./cases/block_string/empty_line.mical");
    let snapshot = utils::make_snapshot("block_string/empty_line", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn end_at_outer() {
    let source = include_str!("./cases/block_string/end_at_outer.mical");
    let snapshot = utils::make_snapshot("block_string/end_at_outer", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn eof() {
    let source = include_str!("./cases/block_string/eof.mical");
    let snapshot = utils::make_snapshot("block_string/eof", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn extra_indent() {
    let source = include_str!("./cases/block_string/extra_indent.mical");
    let snapshot = utils::make_snapshot("block_string/extra_indent", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn fold_style() {
    let source = include_str!("./cases/block_string/fold_style.mical");
    let snapshot = utils::make_snapshot("block_string/fold_style", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn insufficient_indent() {
    let source = include_str!("./cases/block_string/insufficient_indent.mical");
    let snapshot = utils::make_snapshot("block_string/insufficient_indent", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn nested_indent() {
    let source = include_str!("./cases/block_string/nested_indent.mical");
    let snapshot = utils::make_snapshot("block_string/nested_indent", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn whitespace_only_line() {
    let source = include_str!("./cases/block_string/whitespace_only_line.mical");
    let snapshot = utils::make_snapshot("block_string/whitespace_only_line", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn whitespace_only_shallow() {
    let source = include_str!("./cases/block_string/whitespace_only_shallow.mical");
    let snapshot = utils::make_snapshot("block_string/whitespace_only_shallow", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
