//! This file is generated by `cargo codegen parser`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]

mod utils;
#[test]
fn basic_entries() {
    let source = include_str!("../../../test-suite/basic-entries/input.mical");
    let snapshot = utils::make_snapshot("basic-entries", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_clip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-clip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-clip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_keep_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-keep-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-keep-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_folded_strip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-folded-strip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-folded-strip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_clip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-clip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-clip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_keep_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-keep-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-keep-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_none_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_0_literal_strip_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-0-literal-strip-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-0-literal-strip-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_clip_emptyln_none_eof() {
    let source = include_str!("../../../test-suite/block-string-1-folded-clip-emptyln-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-clip-emptyln-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_clip_none_emptyln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-folded-clip-none-emptyln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-clip-none-emptyln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_keep_emptyln_wsln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-folded-keep-emptyln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-keep-emptyln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_keep_none_emptyln_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-folded-keep-none-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-keep-none-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_strip_emptyln_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-folded-strip-emptyln-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-strip-emptyln-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_folded_strip_wsln_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-folded-strip-wsln-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-folded-strip-wsln-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_emptyln_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-emptyln-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-emptyln-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_emptyln_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-emptyln-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-emptyln-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_none_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-none-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-none-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_clip_wsln_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-1-literal-clip-wsln-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-clip-wsln-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_keep_emptyln_wsln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-keep-emptyln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-keep-emptyln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_keep_wsln_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-literal-keep-wsln-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-keep-wsln-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_keep_wsln_none_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-keep-wsln-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-keep-wsln-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_strip_emptyln_emptyln_eof_nonl() {
    let source = include_str!("../../../test-suite/block-string-1-literal-strip-emptyln-emptyln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-strip-emptyln-emptyln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_strip_none_emptyln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-literal-strip-none-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-strip-none-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_1_literal_strip_none_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-1-literal-strip-none-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-1-literal-strip-none-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_body_trailing_whitespace() {
    let source = include_str!("../../../test-suite/block-string-body-trailing-whitespace/input.mical");
    let snapshot = utils::make_snapshot("block-string-body-trailing-whitespace", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_consecutive() {
    let source = include_str!("../../../test-suite/block-string-consecutive/input.mical");
    let snapshot = utils::make_snapshot("block-string-consecutive", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_end_at_outer() {
    let source = include_str!("../../../test-suite/block-string-end-at-outer/input.mical");
    let snapshot = utils::make_snapshot("block-string-end-at-outer", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_extra_indent() {
    let source = include_str!("../../../test-suite/block-string-extra-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-extra-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_fallback() {
    let source = include_str!("../../../test-suite/block-string-fallback/input.mical");
    let snapshot = utils::make_snapshot("block-string-fallback", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded() {
    let source = include_str!("../../../test-suite/block-string-folded/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_folded_strip() {
    let source = include_str!("../../../test-suite/block-string-folded-strip/input.mical");
    let snapshot = utils::make_snapshot("block-string-folded-strip", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_header_trailing_space() {
    let source = include_str!("../../../test-suite/block-string-header-trailing-space/input.mical");
    let snapshot = utils::make_snapshot("block-string-header-trailing-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_in_prefix() {
    let source = include_str!("../../../test-suite/block-string-in-prefix/input.mical");
    let snapshot = utils::make_snapshot("block-string-in-prefix", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_indent() {
    let source = include_str!("../../../test-suite/block-string-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_insufficient_indent() {
    let source = include_str!("../../../test-suite/block-string-insufficient-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-insufficient-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_keep_multi_trailing() {
    let source = include_str!("../../../test-suite/block-string-keep-multi-trailing/input.mical");
    let snapshot = utils::make_snapshot("block-string-keep-multi-trailing", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_clip_emptyln_none_wsln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-clip-emptyln-none-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-clip-emptyln-none-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_clip_wsln_emptyln_emptyln_eof() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-clip-wsln-emptyln-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-clip-wsln-emptyln-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_keep_emptyln_emptyln_none_dedent() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-keep-emptyln-emptyln-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-keep-emptyln-emptyln-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_keep_emptyln_wsln_none_eof() {
    let source = include_str!("../../../test-suite/block-string-multi-folded-keep-emptyln-wsln-none-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-keep-emptyln-wsln-none-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_keep_wsln_wsln_emptyln_dedent() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-keep-wsln-wsln-emptyln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-keep-wsln-wsln-emptyln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_strip_emptyln_emptyln_wsln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-strip-emptyln-emptyln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-strip-emptyln-emptyln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_strip_none_wsln_emptyln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-folded-strip-none-wsln-emptyln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-strip-none-wsln-emptyln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_folded_strip_wsln_none_wsln_dedent() {
    let source = include_str!("../../../test-suite/block-string-multi-folded-strip-wsln-none-wsln-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-folded-strip-wsln-none-wsln-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_clip_none_wsln_wsln_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-literal-clip-none-wsln-wsln-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-clip-none-wsln-wsln-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_clip_wsln_wsln_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-multi-literal-clip-wsln-wsln-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-clip-wsln-wsln-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_keep_none_emptyln_wsln_eof() {
    let source = include_str!("../../../test-suite/block-string-multi-literal-keep-none-emptyln-wsln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-keep-none-emptyln-wsln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_keep_wsln_none_none_eof_nonl() {
    let source =
        include_str!("../../../test-suite/block-string-multi-literal-keep-wsln-none-none-eof-nonl/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-keep-wsln-none-none-eof-nonl", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_strip_emptyln_none_emptyln_eof() {
    let source =
        include_str!("../../../test-suite/block-string-multi-literal-strip-emptyln-none-emptyln-eof/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-strip-emptyln-none-emptyln-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_multi_literal_strip_none_none_none_dedent() {
    let source = include_str!("../../../test-suite/block-string-multi-literal-strip-none-none-none-dedent/input.mical");
    let snapshot = utils::make_snapshot("block-string-multi-literal-strip-none-none-none-dedent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn block_string_nested_indent() {
    let source = include_str!("../../../test-suite/block-string-nested-indent/input.mical");
    let snapshot = utils::make_snapshot("block-string-nested-indent", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn brace_after_key() {
    let source = include_str!("../../../test-suite/brace-after-key/input.mical");
    let snapshot = utils::make_snapshot("brace-after-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn brace_not_block() {
    let source = include_str!("../../../test-suite/brace-not-block/input.mical");
    let snapshot = utils::make_snapshot("brace-not-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn comments_directives() {
    let source = include_str!("../../../test-suite/comments-directives/input.mical");
    let snapshot = utils::make_snapshot("comments-directives", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn directive() {
    let source = include_str!("../../../test-suite/directive/input.mical");
    let snapshot = utils::make_snapshot("directive", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn duplicate_keys() {
    let source = include_str!("../../../test-suite/duplicate-keys/input.mical");
    let snapshot = utils::make_snapshot("duplicate-keys", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn empty() {
    let source = include_str!("../../../test-suite/empty/input.mical");
    let snapshot = utils::make_snapshot("empty", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn hash_edge() {
    let source = include_str!("../../../test-suite/hash-edge/input.mical");
    let snapshot = utils::make_snapshot("hash-edge", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn invalid_escape() {
    let source = include_str!("../../../test-suite/invalid-escape/input.mical");
    let snapshot = utils::make_snapshot("invalid-escape", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_boolean() {
    let source = include_str!("../../../test-suite/key-value-boolean/input.mical");
    let snapshot = utils::make_snapshot("key-value-boolean", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_boolean_at_eof() {
    let source = include_str!("../../../test-suite/key-value-boolean-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-boolean-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_boolean_like() {
    let source = include_str!("../../../test-suite/key-value-boolean-like/input.mical");
    let snapshot = utils::make_snapshot("key-value-boolean-like", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_brace_in_key() {
    let source = include_str!("../../../test-suite/key-value-brace-in-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-brace-in-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_hash_value() {
    let source = include_str!("../../../test-suite/key-value-hash-value/input.mical");
    let snapshot = utils::make_snapshot("key-value-hash-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_indented_quoted_key() {
    let source = include_str!("../../../test-suite/key-value-indented-quoted-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-indented-quoted-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_indented_word_key() {
    let source = include_str!("../../../test-suite/key-value-indented-word-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-indented-word-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_integer() {
    let source = include_str!("../../../test-suite/key-value-integer/input.mical");
    let snapshot = utils::make_snapshot("key-value-integer", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_integer_at_eof() {
    let source = include_str!("../../../test-suite/key-value-integer-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-integer-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_integer_like() {
    let source = include_str!("../../../test-suite/key-value-integer-like/input.mical");
    let snapshot = utils::make_snapshot("key-value-integer-like", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_line_string() {
    let source = include_str!("../../../test-suite/key-value-line-string/input.mical");
    let snapshot = utils::make_snapshot("key-value-line-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_missing_value() {
    let source = include_str!("../../../test-suite/key-value-missing-value/input.mical");
    let snapshot = utils::make_snapshot("key-value-missing-value", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_punct_key() {
    let source = include_str!("../../../test-suite/key-value-punct-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-punct-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_in_line_string() {
    let source = include_str!("../../../test-suite/key-value-quoted-in-line-string/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-in-line-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key() {
    let source = include_str!("../../../test-suite/key-value-quoted-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_empty() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-empty/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-empty", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_unclosed() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-unclosed/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-unclosed", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_unexpected() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-unexpected/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-unexpected", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_key_with_space() {
    let source = include_str!("../../../test-suite/key-value-quoted-key-with-space/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-key-with-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_string() {
    let source = include_str!("../../../test-suite/key-value-quoted-string/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-string", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_value_at_eof() {
    let source = include_str!("../../../test-suite/key-value-quoted-value-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-value-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_quoted_value_trailing() {
    let source = include_str!("../../../test-suite/key-value-quoted-value-trailing/input.mical");
    let snapshot = utils::make_snapshot("key-value-quoted-value-trailing", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_sign_integer_at_eof() {
    let source = include_str!("../../../test-suite/key-value-sign-integer-at-eof/input.mical");
    let snapshot = utils::make_snapshot("key-value-sign-integer-at-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_trailing_space() {
    let source = include_str!("../../../test-suite/key-value-trailing-space/input.mical");
    let snapshot = utils::make_snapshot("key-value-trailing-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_wide_separator() {
    let source = include_str!("../../../test-suite/key-value-wide-separator/input.mical");
    let snapshot = utils::make_snapshot("key-value-wide-separator", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn key_value_word_key() {
    let source = include_str!("../../../test-suite/key-value-word-key/input.mical");
    let snapshot = utils::make_snapshot("key-value-word-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn mixed() {
    let source = include_str!("../../../test-suite/mixed/input.mical");
    let snapshot = utils::make_snapshot("mixed", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn nested_prefix_block() {
    let source = include_str!("../../../test-suite/nested-prefix-block/input.mical");
    let snapshot = utils::make_snapshot("nested-prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn newline() {
    let source = include_str!("../../../test-suite/newline/input.mical");
    let snapshot = utils::make_snapshot("newline", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block() {
    let source = include_str!("../../../test-suite/prefix-block/input.mical");
    let snapshot = utils::make_snapshot("prefix-block", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_after_entry() {
    let source = include_str!("../../../test-suite/prefix-block-after-entry/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-after-entry", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_basic() {
    let source = include_str!("../../../test-suite/prefix-block-basic/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-basic", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_block_string_nested() {
    let source = include_str!("../../../test-suite/prefix-block-block-string-nested/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-block-string-nested", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_close_brace_as_key() {
    let source = include_str!("../../../test-suite/prefix-block-close-brace-as-key/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-close-brace-as-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_deeply_nested() {
    let source = include_str!("../../../test-suite/prefix-block-deeply-nested/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-deeply-nested", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_empty() {
    let source = include_str!("../../../test-suite/prefix-block-empty/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-empty", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_empty_with_eof() {
    let source = include_str!("../../../test-suite/prefix-block-empty-with-eof/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-empty-with-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_eof_no_newline() {
    let source = include_str!("../../../test-suite/prefix-block-eof-no-newline/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-eof-no-newline", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_missing_close() {
    let source = include_str!("../../../test-suite/prefix-block-missing-close/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-missing-close", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_missing_close_with_eof() {
    let source = include_str!("../../../test-suite/prefix-block-missing-close-with-eof/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-missing-close-with-eof", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_multiple() {
    let source = include_str!("../../../test-suite/prefix-block-multiple/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-multiple", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_nested() {
    let source = include_str!("../../../test-suite/prefix-block-nested/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-nested", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_quoted_key() {
    let source = include_str!("../../../test-suite/prefix-block-quoted-key/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-quoted-key", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_trailing_space() {
    let source = include_str!("../../../test-suite/prefix-block-trailing-space/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-trailing-space", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_values() {
    let source = include_str!("../../../test-suite/prefix-block-values/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-values", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn prefix_block_with_values() {
    let source = include_str!("../../../test-suite/prefix-block-with-values/input.mical");
    let snapshot = utils::make_snapshot("prefix-block-with-values", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_keys() {
    let source = include_str!("../../../test-suite/quoted-keys/input.mical");
    let snapshot = utils::make_snapshot("quoted-keys", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn quoted_strings() {
    let source = include_str!("../../../test-suite/quoted-strings/input.mical");
    let snapshot = utils::make_snapshot("quoted-strings", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn shebang() {
    let source = include_str!("../../../test-suite/shebang/input.mical");
    let snapshot = utils::make_snapshot("shebang", source);
    utils::assert_snapshot!(snapshot);
}
#[test]
fn typed_values() {
    let source = include_str!("../../../test-suite/typed-values/input.mical");
    let snapshot = utils::make_snapshot("typed-values", source);
    utils::assert_snapshot!(snapshot);
}
