//! This file is generated by `cargo codegen parser`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]

mod utils;
const GROUP: &str = "prefix_block";
#[test]
fn after_entry() {
    let source = include_str!("./cases/prefix_block/after_entry.mical");
    let snapshot = utils::make_snapshot("prefix_block/after_entry", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn basic() {
    let source = include_str!("./cases/prefix_block/basic.mical");
    let snapshot = utils::make_snapshot("prefix_block/basic", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn close_brace_as_key() {
    let source = include_str!("./cases/prefix_block/close_brace_as_key.mical");
    let snapshot = utils::make_snapshot("prefix_block/close_brace_as_key", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn empty() {
    let source = include_str!("./cases/prefix_block/empty.mical");
    let snapshot = utils::make_snapshot("prefix_block/empty", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn empty_with_eof() {
    let source = include_str!("./cases/prefix_block/empty_with_eof.mical");
    let snapshot = utils::make_snapshot("prefix_block/empty_with_eof", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn missing_close() {
    let source = include_str!("./cases/prefix_block/missing_close.mical");
    let snapshot = utils::make_snapshot("prefix_block/missing_close", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn missing_close_with_eof() {
    let source = include_str!("./cases/prefix_block/missing_close_with_eof.mical");
    let snapshot = utils::make_snapshot("prefix_block/missing_close_with_eof", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn multiple() {
    let source = include_str!("./cases/prefix_block/multiple.mical");
    let snapshot = utils::make_snapshot("prefix_block/multiple", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn nested() {
    let source = include_str!("./cases/prefix_block/nested.mical");
    let snapshot = utils::make_snapshot("prefix_block/nested", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn quoted_key() {
    let source = include_str!("./cases/prefix_block/quoted_key.mical");
    let snapshot = utils::make_snapshot("prefix_block/quoted_key", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn trailing_space() {
    let source = include_str!("./cases/prefix_block/trailing_space.mical");
    let snapshot = utils::make_snapshot("prefix_block/trailing_space", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
#[test]
fn with_values() {
    let source = include_str!("./cases/prefix_block/with_values.mical");
    let snapshot = utils::make_snapshot("prefix_block/with_values", source);
    utils::assert_snapshot!(GROUP, snapshot);
}
