use super::{ensure_file_contents, rustfmt};
use crate::project_root;

use anyhow::Result;
use quote::{format_ident, quote};
use xshell::Shell;

const GENERATED_HEADER: &str = r##"
//! This file is generated by `cargo codegen parser`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]
"##;

pub(crate) fn generate(sh: &Shell, check: bool) -> Result<()> {
    let suite_dir = project_root().join("test-suite");
    let tests_dir = project_root().join("crates/parser/tests");

    let cases = super::collect_test_suite_cases(&suite_dir)?;

    let test_fns = cases.iter().map(|case| {
        let fn_name = format_ident!("{}", case.replace('-', "_"));
        let include_path = format!("../../../test-suite/{case}/input.mical");
        quote! {
            #[test]
            fn #fn_name() {
                let source = include_str!(#include_path);
                let snapshot = utils::make_snapshot(#case, source);
                utils::assert_snapshot!(snapshot);
            }
        }
    });
    let code = quote! {
        mod utils;
        #(#test_fns)*
    };
    let formatted = rustfmt(sh, code.to_string())?;
    ensure_file_contents(
        &tests_dir.join("snapshots.rs"),
        &format!("{}\n{}", GENERATED_HEADER.trim_start(), formatted),
        check,
    )?;

    Ok(())
}
