//! This file is generated by `cargo codegen syntax`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]

#[allow(bad_style)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(u8)]
pub enum SyntaxKind {
    COMMENT,
    DOUBLE_QUOTE,
    FALSE,
    GT,
    MINUS,
    NEWLINE,
    NUMERAL,
    PIPE,
    PLUS,
    SHARP,
    SINGLE_QUOTE,
    SPACE,
    STRING,
    TAB,
    TRUE,
    WORD,
    BLOCK_STRING,
    BLOCK_STRING_HEADER,
    BOOLEAN,
    DIRECTIVE,
    ENTRY,
    ERROR,
    INTEGER,
    LINE_STRING,
    PREFIX_BLOCK,
    QUOTED_KEY,
    QUOTED_STRING,
    SOURCE_FILE,
    WORD_KEY,
}

impl SyntaxKind {
    pub const COUNT: usize = 29usize;
}
impl From<SyntaxKind> for ::rowan::SyntaxKind {
    fn from(kind: SyntaxKind) -> Self {
        Self(kind as u16)
    }
}
impl From<::rowan::SyntaxKind> for SyntaxKind {
    fn from(kind: ::rowan::SyntaxKind) -> Self {
        assert!(kind.0 < (29usize as u16), "bad SyntaxKind: {:?}", kind);
        unsafe { ::core::mem::transmute(kind.0 as u8) }
    }
}

#[macro_export]
#[doc(hidden)]
macro_rules! __token_kind_fast_accsess {
    ('\t') => {
        $crate::SyntaxKind::TAB
    };
    ('\n') => {
        $crate::SyntaxKind::NEWLINE
    };
    (' ') => {
        $crate::SyntaxKind::SPACE
    };
    (comment) => {
        $crate::SyntaxKind::COMMENT
    };
    (#) => {
        $crate::SyntaxKind::SHARP
    };
    (word) => {
        $crate::SyntaxKind::WORD
    };
    ('"') => {
        $crate::SyntaxKind::DOUBLE_QUOTE
    };
    ('\'') => {
        $crate::SyntaxKind::SINGLE_QUOTE
    };
    (string) => {
        $crate::SyntaxKind::STRING
    };
    (+) => {
        $crate::SyntaxKind::PLUS
    };
    (-) => {
        $crate::SyntaxKind::MINUS
    };
    (numeral) => {
        $crate::SyntaxKind::NUMERAL
    };
    (true) => {
        $crate::SyntaxKind::TRUE
    };
    (false) => {
        $crate::SyntaxKind::FALSE
    };
    (|) => {
        $crate::SyntaxKind::PIPE
    };
    (>) => {
        $crate::SyntaxKind::GT
    };
}
pub use __token_kind_fast_accsess as T;
