//! This file is generated by `cargo codegen syntax`, do not edit by hand.
#![cfg_attr(rustfmt, rustfmt::skip)]

#[allow(bad_style)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(u8)]
pub enum SyntaxKind {
    BACKSLASH,
    CLOSE_BRACE,
    FALSE,
    GT,
    MINUS,
    NEWLINE,
    NUMERAL,
    OPEN_BRACE,
    PIPE,
    PLUS,
    SHARP,
    SHEBANG,
    SPACE,
    TAB,
    TRUE,
    WORD,
    BLOCK_STRING,
    BLOCK_STRING_HEADER,
    BOOLEAN,
    COMMENT,
    DIRECTIVE,
    ENTRY,
    ERROR,
    INTEGER,
    KEY,
    LINE_STRING,
    PREFIX_BLOCK,
    SOURCE_FILE,
}

impl From<SyntaxKind> for ::rowan::SyntaxKind {
    fn from(kind: SyntaxKind) -> Self {
        Self(kind as u16)
    }
}
impl From<::rowan::SyntaxKind> for SyntaxKind {
    fn from(kind: ::rowan::SyntaxKind) -> Self {
        assert!(kind.0 < (28usize as u16), "bad SyntaxKind: {:?}", kind);
        unsafe { ::core::mem::transmute(kind.0 as u8) }
    }
}

#[macro_export]
#[doc(hidden)]
macro_rules! __token_kind_fast_accsess {
    ('\t') => {
        $crate::SyntaxKind::TAB
    };
    ('\n') => {
        $crate::SyntaxKind::NEWLINE
    };
    (' ') => {
        $crate::SyntaxKind::SPACE
    };
    ('\\') => {
        $crate::SyntaxKind::BACKSLASH
    };
    (shebang) => {
        $crate::SyntaxKind::SHEBANG
    };
    ('{') => {
        $crate::SyntaxKind::OPEN_BRACE
    };
    ('}') => {
        $crate::SyntaxKind::CLOSE_BRACE
    };
    ('#') => {
        $crate::SyntaxKind::SHARP
    };
    (word) => {
        $crate::SyntaxKind::WORD
    };
    (numeral) => {
        $crate::SyntaxKind::NUMERAL
    };
    (true) => {
        $crate::SyntaxKind::TRUE
    };
    (false) => {
        $crate::SyntaxKind::FALSE
    };
    ('+') => {
        $crate::SyntaxKind::PLUS
    };
    ('-') => {
        $crate::SyntaxKind::MINUS
    };
    ('|') => {
        $crate::SyntaxKind::PIPE
    };
    ('>') => {
        $crate::SyntaxKind::GT
    };
}
pub use __token_kind_fast_accsess as T;
